### ISSUE TITLE
spaces in context of poetry (both `head` and  within `lg`) not displayed

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#105]
see https://auden-musulin-papers.github.io/amp-app-dev/amp-transcript__0039.html?img=off&tab=3&int=on&del=on&udl=on&ucl=on&wsp=on

**Comment by linxOD** [comment]
I added better handling for head and lg. However, space with extent=undefined quantity of characters will not provide any extra whitespaces. space elements with a specified quantity will appear.

**Comment by timofruehwirth** [comment]
memo to us:
with value undefined quantity, add minimum 1 unit so that website can present it

**Comment by timofruehwirth** [comment]
we have now added in `space` elements that have @extent "undefined quantity of characters" an additional @min of "1"
