### ISSUE TITLE
pls review (and revise if necessary) release note amp-app v0.5.0 data/meta/release_note_v0-5-0.md

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#106]
https://github.com/Auden-Musulin-Papers/amp-data/blob/405de4ab2fd4fd1c26a40d33c5a7cf06f9e3f095/data/meta/release_note_v0-5-0.md

**Comment by linxOD** [comment]
looks good. I will add the automated report based on the issues we closed and commits added when releasing the app.

**Comment by linxOD** [comment]
Maybe one thing: The updates to the ODD where quite extensive but maybe we want to wait till we added the description inside the odd before we annouce it?

**Comment by timofruehwirth** [comment]
Yes can you pls write a few sentences into the release note on this, as
### 1.4 ODD

**Comment by linxOD** [comment]
https://github.com/Auden-Musulin-Papers/amp-data/commit/bf4104dbc8f35fa06f69f7b67302a2baa278664f
