### ISSUE TITLE
page break in paragraphs doesn't work

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app#118]
in letters (such as 0063) where the paragraph is interrupted by a page break, we used `<p prev="true">`, however, on the website we have in the first page the whole transcription as if it wasn't any page break and in the second page the correct transcription.
Could you please check what could be wrong?

**Comment by linxOD** [comment]
requires extensive testing. Please check all documents where you added p@prev=true.
