### ISSUE TITLE
fetch facs-img-data from ARCHE instead of ACDH-IIIF

### ISSUE THREAD

**Issue by csae8092** [Auden-Musulin-Papers/amp-app#12]
https://id.acdh.oeaw.ac.at/auden-musulin-papers/amp_0003.jpg?format=iiif -> https://loris.acdh.oeaw.ac.at/uuid:/auden-musulin-papers/amp_0003.jpg/full/full/0/default.jpg

(should work similar to kretschmar project)

**Comment by linxOD** [comment]
closed with commit 76e301c3d8a0ea99260de6639537609912eb25e1
