### ISSUE TITLE
wrong spelling in title of comment pop-up box (document 0006) ("Wadl" instead of "Wandl")

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#121]
where are titles of comments fetched from?

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/e0405ec2-1df8-44f4-bbcf-d1c0efad4950)

**Comment by linxOD** [comment]
since Label and Description is taken from your interp note please check for spelling errors in amp-data

**Comment by timofruehwirth** [comment]
no instance of erroneous spelling in our XML
