### ISSUE TITLE
double title in comment to which two passages refer (how can we make more readable?)

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#124]
![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/bc6826eb-c10f-4b41-bcec-c6706bf1fb4d)

**Comment by linxOD** [comment]
please add more information about which document(s) the specific case is part of.

**Comment by timofruehwirth** [comment]
issue resolved, thank you
