### ISSUE TITLE
In longer poems page break doesn't work (doc0038)

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app#126]
https://auden-musulin-papers.github.io/amp-app-dev/amp-transcript__0038.html?tab=3&int=on

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/42061592/42bb32da-7e3e-498b-b7a7-b47bba9046ad)

**Comment by timofruehwirth** [comment]
this issue is resolved, thank you
