### ISSUE TITLE
Presenting info in comments

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app#127]
Could you please add a space between `string` and `bibl` so that the formalized bibliographical resouce will not appear as part of the string?

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/42061592/73c097fd-33f2-49e4-8caa-825762f376ca)

**Comment by linxOD** [comment]
please add additional information. E.g. doc number that includes this interp example.

**Comment by demigrigo** [comment]
apologies, doc0039

**Comment by linxOD** [comment]
note: [bibl]/editor does not contain any string... optional handling via denormalize script

**Comment by timofruehwirth** [comment]
issue is resolved, thank you
