### ISSUE TITLE
how can links to other documents and to external websites be displayed in the context of `bibl` in `desc` in `interp`?

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#137]
eg doc 0001:

our current solution (we want URL displayed):
```
                        <bibl sameAs="https://www.ogl.at/programm/aktuelles-programm/archiv/1963/5">
                           <title>Programm</title>
                           <orgName ref="#amp_organization_9"/>
                        </bibl>
```

**Comment by linxOD** [comment]
added some handling see #130 
currently bibl is expected to have a title. In any case a link symbol with a link are added.

**Comment by timofruehwirth** [comment]
thank you, we have added a `title` and changed @sameAs to @source for the `bibl`
we still need the name of the organization displayed as fetched from Baserow

**Comment by linxOD** [comment]
We should probably discuss the fetching data from baserow (which is actually fetching data from the TE/XML Index files). 
The main questions is if entites that are only mentioned in the metadata on not the author(s) should become part of TEI/back?
So far the tei:back element only contains entities mentioned by author(s).

**Comment by timofruehwirth** [comment]
works now, thank you, resolved
