### ISSUE TITLE
rename 'Sortierung' to 'Filter by...'

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app#148]
In the results feature from 'Full Text Search' there is the german word for 'filter by' please rename it, thank you
 
![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/42061592/4fc16722-ecde-4c77-aace-f56d4a64bda7)

**Comment by linxOD** [comment]
changed to "Sort by". this is not a filter.

**Comment by timofruehwirth** [comment]
resolved, thank you
