### ISSUE TITLE
display `date` element in same line as `space` preceding it (rather than in next line)

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#164]
in doc 0061 (same thing in doc 0030):

```
                <div type="letter_message">
                     <opener>
                         <dateline>
                             <placeName>
                                 <seg hand="#printed">
                                     <address>   
                                        <rs type="place" ref="#amp_place_id_11">NEULINGGASSE 26/14<lb/>
                                        1030 WIEN</rs><lb/>
                                        <addrLine>TEL. 73 94 015</addrLine>
                                     </address>
                                 </seg>
                             </placeName>
                             <space quantity="44" unit="char"/><date rend="#block">5. April 1977</date>
                         </dateline>
                     </opener>
                </div>
```

**Comment by timofruehwirth** [comment]
this is a solution that works (from doc 0031):
`<space quantity="46" unit="char"/><date rend="#inline">15 De<del>d</del>cember 1985.</date>`

however, this is more like bending the data to the representation ...

**Comment by timofruehwirth** [comment]
in doc 0030 and 0062, the `date` element is a "block" element as defined in other correspondence too, ie, stands on its own and not next to placename
-> we need a solution that can display the `date` element next to `space` preceding it, also if it has @rend="block"

we do not use the @rend="block"  attribute on any other elements

**Comment by linxOD** [comment]
CSS rules that apply to "display: block: An element that has the display property set to block starts on a new line and takes up the available screen width."

**Comment by timofruehwirth** [comment]
let's discuss this in our meet-up

**Comment by timofruehwirth** [comment]
memo to us (solution doc 0030):

```
                     <dateline>
                        <ab rend="#block">
                           <space quantity="40" unit="char"/><date>29th November 1985.</date>
                        </ab>
```
(same solution not possible eg in doc 0061)
