### ISSUE TITLE
rename title for link in literary work to `URL`

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#168]
title for link to Mediathek in doc0060 wrongly displayed as `Wikidata`

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/1d818ad0-4114-4e5d-a74f-9a58a697d6b2)

**Comment by timofruehwirth** [comment]
rename into `URI or URL`

**Comment by linxOD** [comment]
7f09495714ee38eb58879e0b1643d837de02d802

**Comment by timofruehwirth** [comment]
thank you, but please replace `URL|Other ` with `URL` because of readability

**Comment by timofruehwirth** [comment]
thanks for the update
