### ISSUE TITLE
correspondence ODD: `opener` should be only optional at beginning of `div type="letter_message"`

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#169]
see 2nd `div type="letter_message"` -> in doc 33 (on page 1v of the aerogram, letter message continues after addresses)

-> does not validate
-> is not displayed

**Comment by linxOD** [comment]
bd096c030e7c15b6c5364a6ea6299c15204d8248

**Comment by timofruehwirth** [comment]
thank you, works!
