### ISSUE TITLE
pls rework suggested citation in document metadata view on web app

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#175]
header: `Cite this Source (Chicago Manual of Style)`

surname, forename. year of composition/2024. "individual resource title." In *Auden Musulin Papers: A Digital Edition of W. H. Auden's Letters to Stella Musulin*, edited by Sandra Mayer, Timo Frühwirth, Dimitra Grigoriou, Edward Mendelson, Peter Andorfer, and Daniel Elsner. Vienna: Austrian Centre for Digital Humanities and Cultural Heritage, Austrian Academy of Sciences. PID.

for example (doc 0070):

Auden, W. H. 1959/2024. "Typed Letter Signed W. H. Auden to Stella Musulin 1959-10-10." In *Auden Musulin Papers: A Digital Edition of W. H. Auden's Letters to Stella Musulin*, edited by Sandra Mayer, Timo Frühwirth, Dimitra Grigoriou, Edward Mendelson, Peter Andorfer, and Daniel Elsner. Vienna: Austrian Centre for Digital Humanities and Cultural Heritage, Austrian Academy of Sciences. https://hdl.handle.net/21.11115/0000-000E-C30C-9.

**Comment by linxOD** [comment]
instead of "Auden, W. H." 1959/2024. is used the author(s) mentioned in titleStmt?

**Comment by timofruehwirth** [comment]
citation looks very good, but there is a problem with the date of origin (after author names): eg in doc 0047, the text was composed in 1965, but the citation looks like this:
![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/7b7b5d2e-6c8e-4d10-b94e-046b8983eec8)

**Comment by timofruehwirth** [comment]
super, works perfectly now
