### ISSUE TITLE
Faulty display of lines in doc 0047

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#178]
![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/8e52e75d-18bc-4549-ad45-55f015abfec6)

**Comment by linxOD** [comment]
the paragraph breaks because you added a tei:head element inside a tei:p. This is not allowed and therefore please find another solution. I currently added a provisional handling for such cases and the App will look ok.

**Comment by timofruehwirth** [comment]
yes that's true, we still have to rework it (as it is prose within correspondence); for the prose ODD we aim for having `title` after the fist `pb` and before the first `p` ...
