### ISSUE TITLE
`[ ]` representing `<gap/>` should only be displayed if "Original text features" are enabled

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#185]
for example `<gap quantity="1" unit="char" reason="illegible"/>` in line 2958 in doc 0062

(NB: in most other cases, the gap is part of a deletion and therefore not displayed if "Original text features" are disabled)

**Comment by linxOD** [comment]
current logic: a gap@reason=illegible will not be hidden but is always visible while a gap@reason=deleted will be hidden

should this logic change?
if yes, this will affect all other gap elements.

**Comment by timofruehwirth** [comment]
yes, you're right, let's stick with the current logic ...
