### ISSUE TITLE
display of `<listPlace type="choice">` in `interp`

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#191]
we would like to have this (from doc 0028, ana_047)

```
                        <listBibl type="choice">
                           <bibl sameAs="acdh:amp-index-works.xml#lit_work_id_108"/>
                           <bibl sameAs="acdh:amp-index-works.xml#lit_work_id_47"/>
                        </listBibl>
```

displayed in the same way like this (from doc 0053, ana_021)
```
                                <listPlace type="choice">
                                    <place sameAs="acdh:amp-index-places.xml#amp_place_id_7"/>
                                    <place sameAs="acdh:amp-index-places.xml#amp_place_id_258"/>
                                </listPlace>
```
namely entity names plus links to entity detail pages
![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/95fd4f25-66c4-4265-8ca1-c1c1bac8e589)

**Comment by linxOD** [comment]
The two titles of the bibl elements are displayed. What should be changed?
The only difference is the link symbol and a little extra margin between.

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/74879332/c458a897-e861-41d9-9f42-0e982dd51307)

**Comment by timofruehwirth** [comment]
thank you, works now (earlier only links, but no titles, were displayed)
