### ISSUE TITLE
Passage missing

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app#199]
In doc 0028 page 17r the passage before the arrows is missing :(

![image](https://github.com/Auden-Musulin-Papers/amp-data/assets/42061592/073ed706-e6a5-4749-ad35-b45897b5d194)

**Comment by linxOD** [comment]
1455cdf41c3fc4cc4ef281fd94cd784cfceace50

**Comment by demigrigo** [comment]
danke :)
