### ISSUE TITLE
word doesn't show when enclosed in 'ref'

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app#203]
the word 'letter' enclosed in <ref target="..."/> doesn't appear on the app (doc 0062 p 9r)

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/42061592/d9bbfa5f-a341-4bd9-9a8b-e095c574a40c)

**Comment by demigrigo** [comment]
same in comments (@ana_039 in p17r, doc 0062)

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/42061592/876a2d4e-d7ff-49a5-bb20-e0ec95e55634)

**Comment by demigrigo** [comment]
however, I just noticed that in some case the symbol works: 
in doc 0062 p 26r

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/42061592/6ab5d0e2-661a-4e9e-ac95-fe218a5ffd5c)

**Comment by timofruehwirth** [comment]
thank you, issue resolved
