### ISSUE TITLE
Symbol doesn't work

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app#204]
Link symbol for "quote" doesn't work, doc 0062 p 15r

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/42061592/10e24e64-d0bc-4dc8-9688-9dd03fd65f44)

**Comment by timofruehwirth** [comment]
however, I just noticed that in some case the symbol works: 
in doc 0062 p 26r

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/42061592/6ab5d0e2-661a-4e9e-ac95-fe218a5ffd5c)

**Comment by timofruehwirth** [comment]
on the other hand, `<quote source="acdh:amp-transcript__0010.xml">` does not link to doc 0010 (example from doc 0038, line 618)

**Comment by linxOD** [comment]
> on the other hand, `<quote source="acdh:amp-transcript__0010.xml">` does not link to doc 0010 (example from doc 0038, line 618)

There is not quote that links to 0010 in doc 0038 and this doc has only about 300 lines.
