### ISSUE TITLE
page number "11" in doc 0062 not displayed

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#210]
do you have any idea why this page number ("11") is not displayed? in doc 0062, lines 1115-1120:

```
            <div type="prose">
               <fw type="pageNum">
                  <space quantity="27" unit="char"/>11
               </fw>
               <p prev="true">
                  all the main literary works in the German language under review<lb/>
```
can this have to do with the opening `div`?

**Comment by timofruehwirth** [comment]
page number is still not represented as other page numbers:
```
            <pb facs="https://iiif.acdh.oeaw.ac.at/amp/amp_0373/" type="sheet" ed="11r"/>
            <div type="prose">
               <fw type="pageNum">
                  <space quantity="27" unit="char"/>11
               </fw>
               <p prev="true">
```
is represented as:
![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/a2dc0a92-a9da-4943-86b7-b0d29e65c60a)

**Comment by demigrigo** [comment]
same in doc0028 p2r 

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/42061592/f9d37b6a-cf5f-4480-9785-2c766e44eaf3)

**Comment by demigrigo** [comment]
could you please take a look at doc0028 12r; there is also another problem

**Comment by demigrigo** [comment]
thank you!! looks fantastic *-*
