### ISSUE TITLE
solution for displaying added underline needed

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#213]
`<add place="inline">&#x332;</add>m<add place="inline">&#x332;</add>y` (word "my" subsequently underlined, doc 0043, line 354) - yesterday both letters were underlined (this is what we want to achieve), today letter "m" is underlined twice, letter "y" is not underlined:

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/32b3486f-972d-4df5-b760-db04b975732f)

**Comment by timofruehwirth** [comment]
underlines are displaced by 1/2 space to the right

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/44048050-d14d-43fa-8348-5fbc1cd4d408)

**Comment by linxOD** [comment]
as discussed a better solution to add underlines is:

* wrap the word or phrases in e.g. `<hi xml:id="ad_underline1">...</hi>` using an id for identification
* create an `<add>` element at the end of the page or document 
  * `<add>` does not contain any characters 
  * use attribues `rend="line"` and `place="below"` the define the underline
  * to refer to the id of the `hi` elemnt use `corresp=#ad_unline1"`
