### ISSUE TITLE
addition of accent symbol via Unicode

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#215]
doc 0043, line 461

`to be politically 'engag<add place="inline">&#x301;</add>e',`  marks up an added accent over the second "e"; currently displayed above "g"

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/8d3d2b43-10a5-4def-a0be-7f3bbe1dcae4)

**Comment by demigrigo** [comment]
solved thank us @timofruehwirth ;)
