### ISSUE TITLE
added double underline displaced when underline display is enabled

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#217]
doc 0062, line 577:

`                  <space quantity="17" unit="char"/><rs type="lit_work" ref="#lit_work_id_47" ana="acdh:amp-transcript__0031.xml#ana_030"><hi rend="underline">The Years in Au</hi>&#x333;s<hi rend="underline">tria.</hi></rs>
`

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/343e22df-8518-47e4-a219-3303a65209e5)

facsimile:
![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/9e2b5b99-6bd6-4e90-9005-1d0e59ddbfe8)

**Comment by linxOD** [comment]
I do not have any control over unicodes.

**Comment by demigrigo** [comment]
can you @linxOD,  help us find a solution: problem is not the unicode sign, it is rather that the unicode sign is misplaced when the underline is activated
