### ISSUE TITLE
change in display options (3): pls remove `original spelling` slider

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#219]
no <sic>/<corr> markup will be done

explanation: we have decided to fully adopt the 'digital documentary edition' approach (as introduced by Pierazzo)

**Comment by linxOD** [comment]
how to display tei:orig and tei:reg? show tei:reg or both?

**Comment by demigrigo** [comment]
thank you; it looks super!
re: comment we won't use orig and reg [neither will we use sic-cor]
