### ISSUE TITLE
analytics page rework

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#222]
https://amp.acdh.oeaw.ac.at/analytics

- [x] fetch current state of data
- [x] correspondence statistics:
    - [x] only data from Auden Musulin Papers 1959-1973 section of documents
- [ ] network graph
    - [x] interpersonal relationships only as edges, not as nodes (thicker or multiple edges for multiple relationships; perhaps different colors for different types of relationships)
    - [x] perhaps a second network graph regarding organization-person interrelations
    - [ ] rework explanatory texts

**Comment by linxOD** [comment]
- removed relationship ids from nodes -> conncted nodes by relationship type
- downloaded latest data fro person_person table
- relationship type (smaller) node helps the graph in display (i would not remove it)
- different colors is not possible with this library
