### ISSUE TITLE
Search Engine of the app doesn't work properly

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app#223]
I searched for the phrase "Die Presse" and it showed only one result where it should be at least 2

**Comment by linxOD** [comment]
could you add all the documents where "Die Presse" is mentioned, please?

**Comment by demigrigo** [comment]
yes. doc0022, 0053, and 0028

**Comment by linxOD** [comment]
doc 0022 and 0028 are now in the search results; doc 0053 not because "Die Presse" is part of an interp node only.

**Comment by demigrigo** [comment]
thaaank you!! 👯‍♀️
