### ISSUE TITLE
pls find display solution for `add` with @corresp for document 0046

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#239]
- currently not displayed at all
- solution should be similar to how it is done in document 0039

**Comment by linxOD** [comment]
I'm not sure why you are using corresp here? All the add elements are positioned inside the regular text and add the position there are supposed to be.

**Comment by timofruehwirth** [comment]
they are not inline; it's like with the "rev" in doc 0039, they refer to the whole paragraph rather than being inserted into the text (by the other author)
but we can leave it like this, I think
