### ISSUE TITLE
beginning of contents inside `floating text` in doc0028 is not displayed (lines 748-789)

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#242]
this is how it starts (lines 748-757):
```
               <floatingText>
                  <body>
                     <div type="prose">
                        <head>
                           <space quantity="21" unit="char"/><hi rend="underline"><rs type="lit_work" ref="#lit_work_id_106">Declaration</rs>. <hi rend="superscript">1</hi> </hi>
                        </head>
                        <ab>
                           Gentlemen,<lb/>
                        </ab>
                        <p>
```
and footnote `1 The German text was typed on a different machine, and the
separate page joined to the _DDeclaration. ` appears twice now (pages 8r and 10r)

only difference from how `floatingText` is used in doc 0062 (lines 2031 ff): in doc 0062, it's inside a `quote` and it has an `ab` after the `div`
(instead of a `head` as in doc 0028)

**Comment by linxOD** [comment]
testing of docs that include floatingText is required:
* check for elements before and after floatingText
* check if all elements inside floatingText (especially ab) are rendered
* beginning page and ending page of floatingText is critical
* testing of ab elements that follow a floatingText element

**Comment by timofruehwirth** [comment]
works now, thank you
