### ISSUE TITLE
display of text contents duplicated on web app display doc 0039

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#248]
https://amp.acdh.oeaw.ac.at/amp-transcript__0039.html?prs=on&tab=3r&img=on&plc=on&wrk=on&org=on&eve=on&nte=on&qte=on

**Comment by linxOD** [comment]
Could you move this pb: https://github.com/Auden-Musulin-Papers/amp-data/blob/dev/data/editions/amp-transcript__0039.xml#L438 inside the following div type=poem? This would follow the schema applied to the previous two pb elements and resolve the issue.
