### ISSUE TITLE
pls ingest imgs amp_0351.tif - amp_0446.tif into Arche

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#32]

**Comment by csae8092** [comment]
* added missing handle-id for related tei-doc https://github.com/Auden-Musulin-Papers/amp-data/commit/79ea3229f08d1f9e547051377bd58dc97b40c15c
* (re)ingested data

image should be online, please @timofruehwirth reopen if not

**Comment by timofruehwirth** [comment]
@csae8092 , imgs are online, thank you very much!
