### ISSUE TITLE
Update hashtags of photographs

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app#57]
The corresponding hashtags in the landing page of the photos (https://amp.acdh.oeaw.ac.at/photos.html) are stating `#letter `
Could you please update them to state `#photograph` ?
Thank you *-*

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/42061592/06f86ced-253f-4427-928e-5d2128af91e0)

**Comment by linxOD** [comment]
The data is not hard coded but uses the type attribute of the document. Since it is already correct in https://auden-musulin-papers.github.io/amp-app-dev/photos.html we only have to merge the branches and republish the website or re-publish if the merge already happend.
