### ISSUE TITLE
landing page v0.3.0

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#58]
- [x] for v0.3.0 pls replace DALL-E imgs with simple icons fitting the search icon (explanation: the AAD project is being under review and I don't want to trigger any issues regarding taste or, worse, controversial positions on AI-generated contents)
    - for the A-M correspondence something like (all suggestions are CC) https://images.app.goo.gl/ehE3dfVZVXCFt1vD7 or https://images.app.goo.gl/BJieVQKcN8VNrswQ9 or https://images.app.goo.gl/RsntQDKHg67BjZDx8
    - for MaM something like https://images.app.goo.gl/uW8UMta5kg972XqU9 or https://creazilla.com/nodes/3506160-document-89366-the-noun-project-icon or https://creazilla.com/nodes/5299397-document-89367-the-noun-project-icon
    - for photos eg https://images.app.goo.gl/wM7HtafH5pFwZuau7 or https://images.app.goo.gl/a2hyT6ADDKy8gj3W9
    - for computer vision something like https://images.app.goo.gl/xAJNgdTaRUaDLwXc6 or https://images.app.goo.gl/VuQfZhdAxKFzUyuS6
    I generally prefer the slim-style versions to the bold versions unless you have concerns re accessibility

- [x] another point is purely design-related and I accept when you de-prioritize it: when I wrote about 'tiles' in a previous issue, I meant something like: https://images.app.goo.gl/gWbqjckACYZBg8Zc8 or https://images.app.goo.gl/TxTM36HGQEaKKfuV9 (explanation: I don't feel that the semantics of the card design (picking from many cards, as it were) fit the landing-page navigation in the same way as they fit the display of correspondence items) - perhaps we can try for v0.4, I can find good Bootstrap solution if you want ...

**Comment by linxOD** [comment]
tiles or nothing more than cards without border-radius, less margin/padding and uniform color.
