### ISSUE TITLE
monospace font (for #typed) have changed, eg in doc 0062, pls change back

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#76]

**Comment by linxOD** [comment]
I cannot see any difference between production amp and amp-dev in regard to typed = courier new monospace

**Comment by timofruehwirth** [comment]
![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/0433874c-e18c-4998-8500-137819e7671a)
![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/c740174a-155b-40e1-8ab7-b8738b91a6ed)

**Comment by timofruehwirth** [comment]
both is monospace, but different font
