### ISSUE TITLE
bug in display of entity numbers next to buttons in Additional Text Information field

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#90]
number of entities as indicated next to buttons in Additional Text Information field does not match entities in document (eg in doc 0004, 4 work entities are indicated, but none is in the document; same with persons ...)

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/49385e80-b7ad-48c7-a535-df70c1e40e1a)

**Comment by linxOD** [comment]
the additional entities are in the comment (interp) field. Shall I disable entity highlighting in the comments?

**Comment by timofruehwirth** [comment]
ah, ok, in this case: please leave like it is
