### ISSUE TITLE
for organizations that are not mentioned in documents, but only appear in metadata, we need some equivalent to `mentioned in`, indicating in which documents that organization appears in the metadata

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#93]

**Comment by linxOD** [comment]
'rs' is required

**Comment by timofruehwirth** [comment]
inside `orgName`, `persName` etc in `corresDesc`, nest `rs` with @ref (remove @ref from orgName etc)

**Comment by timofruehwirth** [comment]
for post offices within `correspDesc`, see example doc 0059, line 92

**Comment by timofruehwirth** [comment]
updated structure of `orgName` inside `correspDesc`: `rs` referring to org entity now nested within `orgName`

please rename categories in `Correspondence Description` view in web app:
`Sent by:` -> `Sent at:`
`Sent from (Place): ` -> `Sent from:`
`Sent Date: ` -> `Sent at:`
`Received in (Place): ` -> `Received at:`

![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/4b518e0b-c0d8-47d8-94e5-a8ff36d2c0c1)

**Comment by timofruehwirth** [comment]
resolved, many thanks
